### ISSUE TITLE
FE: Prepare knowledge about i18next

### ISSUE THREAD

**Issue by quyn2904** [PiedTeam/NikeCloneTraining-FE-Project#14]

**Comment by tientran1234** [comment]
**1.Giới Thiệu**
 React-i18next là một framework internationalization (quốc tế hóa) mạnh mẽ cho Reactjs/Reactnative dựa trên i18next. Các mô-đun cung cấp nhiều thành phần, ví dụ: để xác nhận rằng các bản dịch cần thiết được tải hoặc nội dung của bạn được hiển thị khi ngôn ngữ thay đổi. Reac-i18next còn phù hợp cho tối ưu serverside rendering. Nó cung cấp thêm nhiều các extension ví dụ như làm việc với next.js. Vì Reac-i18next phụ thuộc vào i18next, bạn cũng có thể sử dụng nó trên bất kỳ các framework UI và máy chủ nào khác (node.js, .net, ...).

**2.Làm thế nào để cài đặt**

># $ npm install i18next --save

> # $ yarn add i18next

**3. Thêm internationalization(quốc tế hóa).**

 Để i18next cấu hình sẵn trong tất cả các component, phải bọc component App bằng component I18nextProvider. Chúng ta cần một phiên bản i18next phải được khởi tạo trước: 
```js
    import React from 'react';
    import ReactDOM from 'react-dom';
    import './index.css';
    import App from './App';
    import {I18nextProvider} from 'react-i18next';
    import i18next from 'i18next';

    i18next.init({
        interpolation: { escapeValue: false },  // React already does escaping
    });

    ReactDOM.render(
        <I18nextProvider i18n={i18next}>
            <App/>
        </I18nextProvider>,
        document.getElementById('root')
    );

```
Ta có thể truyền một namespace mặc định vào hàm translate(), trong ví dụ chúng ta sẽ đặt nó là common. Nếu bạn bỏ qua tham số namespace, bạn phải chỉ định namespace mỗi khi sử dụng để dịch hoặc bạn phải xác định một namespace mặc định trong các tùy chọn i18next.init()
 Trong bước tiếp theo, chúng ta phải bọc các component bằng hàm translate(),khi bạn bọc lại như vậy thì hàm t() sẽ được cung cấp cho tất cả các component ,hàm t() để làm gì ? 
  

>    **Dịch các chuỗi ngôn ngữ: Hàm t() được sử dụng để dịch các chuỗi ngôn ngữ từ tài nguyên dịch được cấu hình trong i18next.** 
>    Ví dụ, nếu bạn có một chuỗi có ID là 'welcome.title', bạn có thể dịch nó bằng cách gọi t('welcome.title').

>    **Truyền tham số cho dịch: Bạn cũng có thể truyền các tham số cho hàm t() để sử dụng trong quá trình dịch.**
>  Ví dụ, nếu bạn muốn dịch chuỗi có chứa biến {username}, bạn có thể gọi t('welcome.message', { username: 'John' }).

> **Thực hiện interpolation: Hàm t() cũng hỗ trợ interpolation, cho phép bạn nhúng các biến vào trong các chuỗi ngôn ngữ.** 
Ví dụ, nếu chuỗi dịch là "Hello, {{username}}!", bạn có thể truyền tham số { username: 'John' } và hàm t() sẽ trả về chuỗi "Hello, John!".

> Fallback cho các chuỗi không dịch: Nếu không tìm thấy bản dịch cho một chuỗi cụ thể, hàm t() có thể trả về một giá trị mặc định hoặc chuỗi gốc, giúp đảm bảo ứng dụng không hiển thị các chuỗi không dịch.

> Xử lý plurals: Hàm t() cũng hỗ trợ xử lý plurals cho các ngôn ngữ có nhiều hình thức số lượng khác nhau.

   

```js
    import { translate, Trans } from 'react-i18next';

    // ... definition of App class ...

    export default translate('common')(App);   // instead of "export default App;"

```
Bây giờ chúng ta phải tìm tất cả các chuỗi ngôn ngữ cụ thể trong ứng dụng . Có hai chuỗi như vậy trong App.js:

```js
    <h1 className="App-title">Welcome to React</h1>
    ...
    To get started, edit <code>src/App.js</code> and save to reload.

```js
Thay thế các chuỗi như dưới đây:
```js
        ...
        <h1 className="App-title">
            { this.props.t('welcome.title', { framework: "react-i18next" }) }
        </h1>
        ...
        <Trans i18nKey='welcome.intro'>
            To get started, edit <code>src/App.js</code> and save to reload.
        </Trans>
        ...

```
Sử dụng hàm t() cho các chuỗi văn bản thuần túy: Đối với các chuỗi ngôn ngữ chỉ chứa văn bản mà không có HTML hoặc biến nào cần được chèn vào, bạn có thể sử dụng hàm this.props.t() để dịch chúng. Ví dụ, trong đoạn mã, this.props.t('welcome.title', { framework: "react-i18next" }) sẽ dịch chuỗi có ID là 'welcome.title'.

Sử dụng <Trans> component cho các chuỗi phức tạp hoặc chứa HTML: Nếu chuỗi ngôn ngữ chứa HTML hoặc cần chèn các biến được định dạng, bạn có thể sử dụng <Trans> component để dịch chúng. Trong ví dụ, <Trans i18nKey='welcome.intro'>...</Trans> được sử dụng để dịch nội dung của một phần tử <Trans> có ID là 'welcome.intro'. Điều này cho phép bạn dịch các chuỗi có cú pháp phức tạp mà không mất đi cấu trúc HTML của chúng.

** 4.Translate cho ứng dụng.**
Các bản dịch của các văn bản tùy chỉnh lộn xộn của chúng ta sẽ được lưu trữ cho mỗi ngôn ngữ trong một thư mục riêng. Đối với mỗi namespace, chúng ta tạo một tệp .json riêng. Hãy tạo các tệp JSON cho bản dịch tiếng Anh và tiếng Đức:

> src/translations/en/common.json
```
       {
            "welcome": {
                "title": "Welcome to {{framework}}",
                "intro": "To get started, edit <1><0></0></1> and save to reload."
            }
        }
```

> src/translations/en/common.json

```js
  {
            "welcome": {
                "title": "Willkommen bei {{framework}}",
                "intro": "Zum Loslegen editiere <1><0></0></1>. Beim Speichern wird die App im Browser automatisch neu geladen."
            }
        }
```
Bây giờ chúng ta có thể tải các tệp JSON này và thêm chúng vào các tùy chọn được truyền vào i18next.init().
```js

    import common_de from "./translations/de/common.json";
    import common_en from "./translations/en/common.json";

    i18next.init({
        interpolation: { escapeValue: false },  // React already does escaping
        lng: 'en',                              // language to use
        resources: {
            en: {
                common: common_en               // 'common' is our custom namespace
            },
            de: {
                common: common_de
            },
        },
    });
```

5. Thay đổi ngôn ngữ
Để tự động chọn ngôn ngữ bạn có thể sử dụng một trong các plugin phát hiện ngôn ngữ được liệt kê trên trang này . Đối với ứng dụng demo của chúng ta, chúng ta chỉ cần thêm hai nút button và kích hoạt thay đổi ngôn ngữ theo cách thủ công. Thêm các dòng sau vào hàm render() trong App.js:

```js
   render()
    {
        const { t, i18n } = this.props;
        return (
            <div>
                ...
                <button onClick={() => i18n.changeLanguage('de')}>de</button>
                <button onClick={() => i18n.changeLanguage('en')}>en</button>
            </div>
        );
    }
```
