### ISSUE TITLE
Write code convention FE

### ISSUE THREAD

**Issue by minhhy2801** [PiedTeam/NikeCloneTraining-FE-Project#6]
Please help add your code convention of FE and BE side
Here is an example in FE for you to have a look:

- File- and component names need to be identical.
- Use PascalCase naming convention for filename as well as component name
- Use lint format suggestation
  - https://eslint.org/docs/latest/use/getting-started
  - Rules of Hooks: [eslint-plugin-react-hooks](https://github.com/facebook/react/tree/master/packages/eslint-plugin-react-hooks)
  - JSX accessibility: [eslint-plugin-jsx-a11y](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y)
  - https://github.com/jsx-eslint/eslint-plugin-react
  - https://typescript-eslint.io/getting-started/
- Use prettier https://prettier.io/
- Use husky https://github.com/typicode/husky
- List rules of commit detail

**Comment by quyn2904** [comment]
### File structure

    .
    ├── public                  # static files
    │   ├── favicon.ico
    │   ├── robots.txt
    ├── src                        # source files
    │   ├── apis                   # api urls
    │   ├── assets                 # static assets
    │   ├── components             # reusable components shared across the app
    │   ├── constants
    │   ├── contexts               # context providers
    │   ├── db                     # fake database
    │   ├── fonts
    │   ├── hooks                  # custom hooks
    │   ├── pages
    │   |   ├── Homepage
    │   |   |   ├── index.ts                # export page
    │   |   |   ├── HomePage.service.ts     # page service
    │   |   |   ├── HomePage.tsx            # page component
    │   ├── redux                 # redux
    │   ├── styles                 # global styles
    │   ├── ui                     # reusable UI components
    │   ├── utils                  # helper functions
    │   ├── widgets                # reusable widgets
    │   ├── App.tsx                # main app component
    │   ├── index.tsx              # app entry point
    ├── .editorconfig              # editor config
    ├── .eslintignore              # eslint ignore
    ├── .eslintrc.cjs              # eslint config
    ├── .gitignore                 # git ignore
    ├── .prettierignore            # prettier ignore
    ├── .prettierrc                # prettier config
    ├── index.html                 # main html file
    ├── postcss.config.js          # postcss config for tailwind
    ├── tailwind.config.js         # tailwind config where you can add additional colors, fonts, etc.
    ├── tsconfig.json              # tsconfig for IDE
    ├── package.json
    ├── vite.config.js

### Basic Rules

    - Một file chỉ được định nghĩa một Component
    - Luôn luôn sử dụng JSX syntax

### Naming:

    - Tên file và tên component phải giống nhau
    - Sử dụng chuẩn PascalCase. VD: GlobalHeader.tsx
    - tên phải mô tả rõ mục đích của chúng

### Create và export components:

    - Tạo component bằng arrow function. VD: const MessageItem = () => {}
    - Export components ở cuối file
    - Tạo types khai báo rõ parameter của component

### Import

    - Import theo thứ tự: utils, styles, fonts, contexts, hooks, components, pages
    - Khi import phải chia các đường dẫn import theo chức năng
    - Example:
        //utils
        import { lazy, Suspense, useEffect, useRef } from 'react'

        //styles
        import '@styles/index.scss'
        import ThemeStyles from '@styles/theme'

        //contexts
        import { SidebarProvider } from '@contexts/sidebarContext'
        import { ThemeProvider } from 'styled-components'

        //hooks
        import { ThemeContextType, useTheme } from '@contexts/themeContext'
        import { Route, Routes, useLocation } from 'react-router-dom'
        import { useWindowSize } from 'react-use'

        //conponents
        import Loader from '@components/Loader'
        import AppBar from '@layout/AppBar'
        import { ToastContainer } from 'react-toastify'

        //pages
        const Login = lazy(() => import('@pages/Login'))

### Thao tác bất đồng bộ

    Dùng async/await thay vì Promise.then()

### Tags:

    - Luôn luôn dùng tag tự đóng nếu không có children
    VD: <Foo className="stuff" />
    - Nếu component có thuộc tính nhiều dòng, đóng tag trên dòng mới

### Handler Methos

    - Đặt tên method theo cú pháp: `"handle" + triggering event`. VD: handleClick
    - Sử dụng arrow function để đảm bảo 'this' luôn trỏ đến context đúng.

**Comment by minhhy2801** [comment]
https://github.com/PiedTeam/NikeCloneTraining-BE-Project/issues/1
